/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'cwzeng' at '7/9/16 11:46 PM' with Gradle 2.14
 *
 * @author cwzeng, @date 7/9/16 11:46 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
